# get python3
FROM python:3.9

# try to install sfepy with pip, get an older version of numpy first
RUN pip install "numpy<2.0"
RUN pip install sfepy

#try to install gmsh (needs some packages for some reason)
RUN apt-get update && apt-get install -y --no-install-recommends \
    gmsh \
    && rm -rf /var/lib/apt/lists/*