ARG UBUNTU_VERSION=24.04
FROM ubuntu:${UBUNTU_VERSION} AS builder

# Install system dependencies including Mesa and development tools
RUN apt-get update  && apt-get install -y \
    cmake \
    file \
    git \
    gcc \
    g++ \
    make \
    build-essential \
    pkg-config \
    python3 \
    bison \
    flex \
    patchelf \
    ninja-build \
    wget \
    curl \
    qtbase5-dev \         
    libfftw3-dev \        
    libeigen3-dev \
    libssl-dev \
    openssl \    
    libboost-dev \        
    libpng-dev \          
    libtiff-dev \        
    libjpeg-dev \         
    libosmesa6-dev \      
    libgl1-mesa-dev \     
    libx11-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*           


#set the environmental variables to use my big /offloaded/tmp as TMP instead of the tiny default one
ENV TMPDIR=/offloaded/tmp
ENV TEMP=/offloaded/tmp
ENV TMP=/offloaded/tmp

# Set the working directory
# permissible if there is a genuine install (or copying of libs/executables) step later
WORKDIR /offloaded/repoDownload

# Clone the ParaView Superbuild repository
RUN if [ ! -d "paraview-superbuild" ]; then git clone https://gitlab.kitware.com/paraview/paraview-superbuild.git; fi
WORKDIR /offloaded/repoDownload/paraview-superbuild
RUN git submodule init
RUN git checkout v5.12.1
RUN git submodule update

# Set the working directory to the ParaView Superbuild directory
WORKDIR /offloaded/repoDownload/paraview-superbuild

# Configure and build ParaView with OSMesa enabled
# ToDo: make mkdir conditional
# RUN mkdir build 
RUN cd build \
    && cmake .. -DParaView_ENABLE_osmesa=ON -DENABLE_paraviewweb=ON \
    && make -j4  

# Set environment variables for ParaView
ENV PATH="/offloaded/repoDownload/paraview-superbuild/build/install/bin:${PATH}"
ENV LD_LIBRARY_PATH="/offloaded/repoDownload/paraview-superbuild/build/install/lib:${LD_LIBRARY_PATH}"
ENV PYTHONPATH=/offloaded/repoDownload/paraview-superbuild/build/install/lib/python3.12/site-packages:$PYTHONPATH


