# Stage 1: Build gmsh from source
FROM python:3.9.25-slim-trixie as gmsh-builder

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    libocct-foundation-dev \
    libocct-data-exchange-dev \
    libocct-modeling-algorithms-dev \
    libocct-modeling-data-dev \
    libocct-ocaf-dev \
    cmake \
    build-essential \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Clone gmsh repository
WORKDIR /gmsh
RUN git clone https://gitlab.onelab.info/gmsh/gmsh.git .

# Create build directory and run cmake with FLTK disabled
# might also use -DENABLE_BUILD_DYNAMIC=1 for gmsh APIs (e.g. Python)
RUN mkdir build && cd build && \
    cmake -DENABLE_FLTK=0 -DENABLE_BUILD_DYNAMIC=0 -DENABLE_OCC=1 .. && \
    make -j$(nproc) && \
    make install

# Stage 2: we now install/build sfepy
FROM python:3.9.25-slim-trixie as sfepy-builder
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

# Upgrade pip and install the wheel package
RUN pip install --upgrade pip wheel

# Download/build sfepy and requirements and store them under /wheels
RUN pip wheel "sfepy" "numpy<2.0" -w /wheels
RUN ls -lah /wheels

# Stage 3: throw everything together
FROM python:3.9.25-slim-trixie

# Copy compiled and installed gmsh files from gmsh-builder
COPY --from=gmsh-builder /usr/local/bin/gmsh /usr/local/bin/gmsh
#COPY --from=gmsh-builder /usr/local /usr/local
# check which libraries gmsh links at runtime (currently commented out) 
# RUN ldd /usr/local/bin/gmsh

# Copy wheels from sfepy-builder and install them
COPY --from=sfepy-builder /wheels /wheels
RUN pip install --no-cache-dir /wheels/*.whl

# get the stuff that gmsh needs to run, extend library path and check again if stuff's present
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    #libocct-foundation-dev \
    #libocct-data-exchange-dev \
    libocct-data-exchange-dev \
    #libocct-modeling-algorithms-dev \
    #libocct-modeling-data-dev \
    #libocct-ocaf-dev \
    && rm -rf /var/lib/apt/lists/*
RUN ldd /usr/local/bin/gmsh
