FROM docker.io/dicehub/openfoam:9

# we will need git...
RUN sudo apt-get update && apt-get install -y --no-install-recommends \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR $HOME/repoDownload

# Clone the repo if needed
# ToDo: make conditional (don't clone if already existing)
RUN git clone https://github.com/fppimenta/rheoTool.git

# Compile
WORKDIR $HOME/repoDownload/rheoTool/of9


RUN "./downloadEigen"
#current missing the writing of eigen folder into .bashrc and the re-sourcing of it

RUN "./installPetsc"
#pretty sure this also has some weird manual steps in it

RUN  "./Allwmake"