ARG UBUNTU_VERSION=24.04
FROM ubuntu:${UBUNTU_VERSION} AS builder

# Install system dependencies including Mesa and development tools
RUN apt-get update  && apt-get install -y \
    cmake \
    file \
    git \
    gcc \
    g++ \
    make \
    build-essential \
    pkg-config \
    python3 \
    bison \
    flex \
    patchelf \
    ninja-build \
    wget \
    curl \
    qtbase5-dev \         
    libfftw3-dev \        
    libeigen3-dev \       
    libboost-dev \        
    libpng-dev \          
    libtiff-dev \        
    libjpeg-dev \         
    libosmesa6-dev \      
    libgl1-mesa-dev \     
    libx11-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*           


#set the environmental variables to use my big /shared/tmp as TMP instead of the tiny default one
ENV TMPDIR=/shared/tmp
ENV TEMP=/shared/tmp
ENV TMP=/shared/tmp

# Set the working directory
WORKDIR /shared/workspace

# Clone the ParaView Superbuild repository
RUN if [ ! -d "paraview-superbuild" ]; then git clone https://gitlab.kitware.com/paraview/paraview-superbuild.git; fi
WORKDIR /shared/workspace/paraview-superbuild
RUN git submodule init && git submodule update

# Set the working directory to the ParaView Superbuild directory
WORKDIR /shared/workspace/paraview-superbuild

# Configure and build ParaView with OSMesa enabled
RUN mkdir build \
    && cd build \
    && cmake .. -DParaView_ENABLE_OSMESA=ON -DENABLE_paraviewweb=ON -Dmesa_USE_SWR=ON -DUSE_SYSTEM_python=ON \
    && make -j4  

# Set environment variables for ParaView
ENV PATH="/shared/workspace/paraview-superbuild/build/install/bin:${PATH}"
ENV LD_LIBRARY_PATH="/shared/workspace/paraview-superbuild/build/install/lib:${LD_LIBRARY_PATH}"
ENV PYTHONPATH=/shared/workspace/paraview-superbuild/build/install/lib/python3.12/site-packages:$PYTHONPATH


# Default command to run ParaView
CMD ["/shared/workspace/paraview-superbuild/build/install/bin/paraview"]
