# USAGE podman build  --network slirp4netns -t superbuild:arm64 .

ARG UBUNTU_VERSION=24.04
FROM ubuntu:${UBUNTU_VERSION} AS base

# Install system dependencies including Mesa and development tools
RUN apt-get update  && apt-get install -y \
    cmake \
    file \
    git \
    gcc \
    g++ \
    make \
    build-essential \
    pkg-config \
    python3 \
    bison \
    flex \
    patchelf \
    ninja-build \
    wget \
    curl \
    qtbase5-dev \         
    libfftw3-dev \        
    libeigen3-dev \       
    libboost-dev \        
    libpng-dev \          
    libtiff-dev \        
    libjpeg-dev \         
    libosmesa6-dev \      
    libgl1-mesa-dev \     
    libx11-dev            

# clean-up (might be unncessary in the long run)
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /workspace

# Clone the ParaView Superbuild repository
RUN if [ ! -d "paraview-superbuild" ]; then git clone https://gitlab.kitware.com/paraview/paraview-superbuild.git; fi
WORKDIR /workspace/paraview-superbuild
RUN git submodule init && git submodule update

# Set the working directory to the ParaView Superbuild directory
WORKDIR /workspace/paraview-superbuild

# Configure and build ParaView with OSMesa enabled
RUN mkdir build \
    && cd build \
    && cmake .. -DParaView_ENABLE_OSMESA=ON -DENABLE_paraviewweb=ON -Dmesa_USE_SWR=OFF -DUSE_SYSTEM_python=ON \
    && make -j4  

# Set environment variables for ParaView
ENV PATH=/workspace/paraview-superbuild/build/bin:$PATH
ENV LD_LIBRARY_PATH=/workspace/paraview-superbuild/build/lib:$LD_LIBRARY_PATH

# Default command to run ParaView
CMD ["/workspace/paraview-superbuild/build/bin/paraview"]
