# grab the container holding the nightly gmsh binary as base
FROM ghcr.io/malteschoen/gmsh:latest

#grab stuff needed for building
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC \
    apt-get install -y --no-install-recommends \
	git \
	build-essential \
	cmake \
	libhdf5-dev \
	doxygen \ 
	graphviz \
   	ca-certificates \
    && rm -rf /var/lib/apt/lists/* 

#take stuff from my standard repo
WORKDIR /shared/workspace
RUN git clone https://github.com/malteschoen/armedMedusa.git --branch dev --single-branch

#rename folder to accomodate python script
RUN mv /shared/workspace/armedMedusa /shared/workspace/medusa
WORKDIR /shared/workspace/medusa

RUN python3 ./run_tests.py