# grab the container holding the nightly gmsh binary as base
# TODO: go to 'latest'
FROM ghcr.io/malteschoen/gmsh:arm64

#grab stuff needed for building
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC \
    apt-get install -y --no-install-recommends \
	git \
	build-essential \
	cmake \
	libhdf5-dev \
	doxygen \ 
	graphviz \
   	ca-certificates \
    && rm -rf /var/lib/apt/lists/* 

WORKDIR /shared/workspace
RUN git clone https://gitlab.com/e62Lab/medusa.git --branch master --single-branch

WORKDIR /shared/workspace/medusa
RUN python3 ./run_tests.py -t