# grab the container holding the nightly gmsh binary as base
# TODO: go to 'latest'
FROM ghcr.io/malteschoen/gmsh:arm64

#grab stuff needed for building
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC \
    apt-get install -y --no-install-recommends \
	git \
	build-essential \
	cmake \
	libhdf5-dev \
	doxygen \ 
	graphviz \
   	ca-certificates \
    && rm -rf /var/lib/apt/lists/* 

WORKDIR /shared/workspace
RUN git https://github.com/malteschoen/armedMedusa.git --branch dev --single-branch

WORKDIR /shared/workspace/medusa
#export LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/hdf5/serial:$LD_LIBRARY_PATH
RUN python3 ./run_tests.py