ARG UBUNTU_VERSION=24.04
FROM ubuntu:${UBUNTU_VERSION} AS builder

# Install dependencies (mainly python and pocl)
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC \
    apt-get install -y --no-install-recommends \
        python3 \
	python3-pip \
	libpocl2 \
	gmsh \
    && rm -rf /var/lib/apt/lists/* 

#break system packages for newer version of Ubuntu
RUN pip3 install --break-system-packages bempp-cl matplotlib
#RUN pip3 install bempp-cl matplotlib