# usage when building image: podman build -t glance:24 .
# usage when running container: podman run -d -p 8080:8080 glance:24
 
# FIRST STAGE: Build environment
FROM node:24 AS builder

# Set the working directory inside the container
WORKDIR /usr/src/app

# Clone the Glance repository
RUN git --version && git clone https://github.com/kitware/glance.git

# Set the working directory to the Glance directory
WORKDIR /usr/src/app/glance

# Install dependencies
RUN npm install &&  npx update-browserslist-db@latest --yes && npm install webpack@latest webpack-cli@latest --save-dev

# Build the project
RUN npm run build:release

# SECOND STAGE: Production environment (lighter image)

# Production environment: serve with Python HTTP server (slimmest possible)
FROM python:3.12-slim

WORKDIR /usr/src/app

# Copy the built application from the builder stage
COPY --from=builder /usr/src/app/glance/dist /usr/src/app/dist

EXPOSE 8080

# Serve content using Python's built-in HTTP server
CMD ["python", "-m", "http.server", "8080", "--directory", "dist"]