FROM docker.io/microfluidica/openfoam:2412

# we will need git...
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /repoDownload

# Clone the repo if needed
# ToDo: make conditional (don't clone if already existing)
RUN git clone https://gitlab.com/interface-tracking/twophaseintertrackfoamrelease.git

# Compile
WORKDIR /repoDownload/twophaseintertrackfoamrelease
RUN ./Allwmake